### ISSUE TITLE
Working on one mac, but not the other

### ISSUE THREAD

**Issue by SLesslyTall** [peteshadbolt/abp#3]
Mac 1:
Working from the git copy, not the pip, and getting this error in the terminal when running `abpserver`:

```
Traceback (most recent call last):
  File "/usr/local/bin/abpserver", line 4, in <module>
    __import__('pkg_resources').run_script('abp==0.4.11', 'abpserver')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 724, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1650, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/site-packages/abp-0.4.11-py2.7.egg/EGG-INFO/scripts/abpserver", line 40, in <module>
    where = os.path.abspath(resource_filename("abp.static", ""))
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1149, in resource_filename
    return get_provider(package_or_requirement).get_resource_filename(
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 424, in get_provider
    __import__(moduleOrReq)
ImportError: No module named static
```

when running nosetests, a few errors also occur:

````
EEEEEEEE
======================================================================
ERROR: Failure: ImportError (No module named anders_briegel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Library/Python/2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Library/Python/2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/sm14824/Repositories/abp/tests/test_against_anders_and_briegel.py", line 2, in <module>
    from anders_briegel import graphsim
ImportError: No module named anders_briegel

======================================================================
ERROR: Failure: ImportError (No module named anders_briegel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Library/Python/2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Library/Python/2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/sm14824/Repositories/abp/tests/test_clifford.py", line 8, in <module>
    from anders_briegel import graphsim
ImportError: No module named anders_briegel

======================================================================
ERROR: Failure: ImportError (No module named anders_briegel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Library/Python/2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Library/Python/2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/sm14824/Repositories/abp/tests/test_fancy.py", line 6, in <module>
    from mock import simple_graph
  File "/Users/sm14824/Repositories/abp/tests/mock.py", line 7, in <module>
    from anders_briegel import graphsim
ImportError: No module named anders_briegel

======================================================================
ERROR: Failure: ImportError (No module named anders_briegel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Library/Python/2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Library/Python/2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/sm14824/Repositories/abp/tests/test_graphstate.py", line 2, in <module>
    import mock
  File "/Users/sm14824/Repositories/abp/tests/mock.py", line 7, in <module>
    from anders_briegel import graphsim
ImportError: No module named anders_briegel

======================================================================
ERROR: Failure: ImportError (No module named anders_briegel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Library/Python/2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Library/Python/2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/sm14824/Repositories/abp/tests/test_measurement.py", line 4, in <module>
    from anders_briegel import graphsim
ImportError: No module named anders_briegel

======================================================================
ERROR: Failure: ImportError (No module named anders_briegel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Library/Python/2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Library/Python/2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/sm14824/Repositories/abp/tests/test_mercedes.py", line 3, in <module>
    from mock import simple_graph
  File "/Users/sm14824/Repositories/abp/tests/mock.py", line 7, in <module>
    from anders_briegel import graphsim
ImportError: No module named anders_briegel

======================================================================
ERROR: Failure: ImportError (No module named anders_briegel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Library/Python/2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Library/Python/2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/sm14824/Repositories/abp/tests/test_qi.py", line 4, in <module>
    import mock
  File "/Users/sm14824/Repositories/abp/tests/mock.py", line 7, in <module>
    from anders_briegel import graphsim
ImportError: No module named anders_briegel

======================================================================
ERROR: Failure: ImportError (No module named anders_briegel)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Library/Python/2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Library/Python/2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/sm14824/Repositories/abp/tests/test_stabilizer.py", line 3, in <module>
    import mock
  File "/Users/sm14824/Repositories/abp/tests/mock.py", line 7, in <module>
    from anders_briegel import graphsim
ImportError: No module named anders_briegel

----------------------------------------------------------------------
Ran 8 tests in 2.007s

FAILED (errors=8)
````

Mac 2: 

Also running from git copy. Running `abpserver` doesn't boot a chrome window, but idles until one opened and manually set to `http://localhost:5001/#`, but otherwise is working ok 

Also has same error messages when running `nosetests`

**Comment by peteshadbolt** [comment]
Re: Mac 2, that's expected behaviour. Do `abpserver -v`. Please split your issues out if possible ...

**Comment by peteshadbolt** [comment]
Also RE: `nosetests`, that's expected - as noted in the README. I use a modified version of A&B's `graphsim` package to test, and that's not included in this repo. I can set things up such that it does not try to run those tests.

I do really wanna get to the bottom of the `static` business though

**Comment by SLesslyTall** [comment]
It seemed to be a problem with the permissions associated with the packages being installed. This seemed to work to solve my problem with mac 1's  install permissions: http://stackoverflow.com/questions/4495120/combine-user-with-prefix-error-with-setup-py-install

Working fine now!
